/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import clases.cliente;
import clases.cuenta;
import clases.transaccion;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rmiclases.interfazRemota;

/**
 *
 * @author Rant AA
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txb = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        txa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txidcli = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txnc = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        txan = new javax.swing.JTextField();
        tcfe = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablon = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cbmes = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        cbtc = new javax.swing.JComboBox<>();
        jButton17 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txidc3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(13, 2, 89));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel16.setText("Cuentas de saldo entre");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txb.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jPanel8.add(txb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 60, -1));

        jButton19.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton19.setText("Buscar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        txa.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jPanel8.add(txa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("A");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 190, 110));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Transacciones del cliente de X Cuenta");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 40));

        txidcli.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jPanel9.add(txidcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 80, -1));

        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ID Cliente");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("#Cuenta");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txnc.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jPanel9.add(txnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 80, -1));

        jButton16.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton16.setText("Buscar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Año");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        txan.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jPanel9.add(txan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 60, -1));

        tcfe.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tcfe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tcfeMouseClicked(evt);
            }
        });
        jPanel9.add(tcfe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 80, -1));

        jLabel33.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Fecha");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 270, 190));

        jScrollPane4.setBackground(new java.awt.Color(1, 4, 64));

        tablon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablon);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 390, 270));

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel17.setText("Transacciones hechas en");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        cbmes.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cbmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));
        cbmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmesActionPerformed(evt);
            }
        });
        jPanel10.add(cbmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jTextField2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jPanel10.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Mes");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Año ");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 280, 110));

        jPanel11.setBackground(new java.awt.Color(0, 153, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel18.setText("Clientes con cuentas de: ");
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        cbtc.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cbtc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Ahorro", "Debito", "Credito" }));
        cbtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtcActionPerformed(evt);
            }
        });
        jPanel11.add(cbtc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        jButton17.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton17.setText("Buscar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 80));

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel19.setText("Cuentas de X Clientes: ");
        jPanel13.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txidc3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jPanel13.add(txidc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 80, -1));

        jLabel26.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel26.setText("ID Cliente");
        jPanel13.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jButton20.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton20.setText("Buscar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 190, 110));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 710, 420));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Consultas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmesActionPerformed

    private void cbtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtcActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        try {

            interfazRemota obje = (interfazRemota) Naming.lookup("rmi://localhost:6060/obje");
            int tipocuenta;
            ArrayList<cliente> clientes;

            if (cbtc.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Debes tener un tipo de cuenta");
                //error
            } else {
                tipocuenta = cbtc.getSelectedIndex();

                clientes = obje.con2(tipocuenta);
                DefaultTableModel dtm = new DefaultTableModel();
                tablon.setModel(dtm);
                String titulos[] = {"NOMBRE", "APATARENO", "AMATERNO", "NUMCTA", "TIPO DE CUENTA", "FECHA EXPEDICION", "SALDO"};

                dtm.setColumnIdentifiers(titulos);
                for (int i = 0; i < clientes.size(); i++) {
                    String valores[] = {clientes.get(i).getNom(), clientes.get(i).getApp(), clientes.get(i).getApm(), String.valueOf(clientes.get(i).getNumc()), clientes.get(i).getTipoc(), clientes.get(i).getFechEx(), String.valueOf(clientes.get(i).getSaldo())};
                    dtm.addRow(valores);
                }
                tablon.setModel(dtm);
            }

        } catch (RemoteException e) {
            System.out.println("Error de invocacion" + e);
        } catch (NotBoundException e) {
            System.out.println("Error de invocacion" + e);
        } catch (MalformedURLException e) {
            System.out.println("Error de invocacion" + e);
        }

    }//GEN-LAST:event_jButton17ActionPerformed

    private void tcfeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcfeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tcfeMouseClicked

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        try {

            interfazRemota obje = (interfazRemota) Naming.lookup("rmi://localhost:6060/obje");
            int idcliente, nc, an;
            ArrayList<transaccion> t = null;
            if (!txidcli.getText().isEmpty() && txnc.getText().isEmpty() && tcfe.getText().isEmpty()) {
                idcliente = Integer.parseInt(txidcli.getText());
                t = obje.con3(idcliente);
                DefaultTableModel dtm = new DefaultTableModel();
                tablon.setModel(dtm);
                String titulos[] = {"Id T", "#Cuenta", "F. Transaccion", "T.Transaccion", "Monto", "ID Cliente", "Nombre",};

                dtm.setColumnIdentifiers(titulos);
                for (int i = 0; i < t.size(); i++) {
                    String valores[] = {String.valueOf(t.get(i).getIdtran()), String.valueOf(t.get(i).getNumcuenta()), t.get(i).getFechaTrans(), t.get(i).getTipoTrans(), String.valueOf(t.get(i).getMonto()), String.valueOf(t.get(i).getIdclie()), t.get(i).getNom()};
                    dtm.addRow(valores);
                }
                tablon.setModel(dtm);
            }
            if (!txidcli.getText().isEmpty() && !txnc.getText().isEmpty() && tcfe.getText().isEmpty()) {
                idcliente = Integer.parseInt(txidcli.getText());
                nc = Integer.parseInt(txnc.getText());
                t = obje.con4(idcliente, nc);
                DefaultTableModel dtm = new DefaultTableModel();
                tablon.setModel(dtm);
                String titulos[] = {"Id T", "#Cuenta", "F. Transaccion", "T.Transaccion", "Monto", "ID Cliente", "Nombre",};

                dtm.setColumnIdentifiers(titulos);
                for (int i = 0; i < t.size(); i++) {
                    String valores[] = {String.valueOf(t.get(i).getIdtran()), String.valueOf(t.get(i).getNumcuenta()), t.get(i).getFechaTrans(), t.get(i).getTipoTrans(), String.valueOf(t.get(i).getMonto()), String.valueOf(t.get(i).getIdclie()), t.get(i).getNom()};
                    dtm.addRow(valores);
                }
                tablon.setModel(dtm);
            }
            if (!txidcli.getText().isEmpty() && !txnc.getText().isEmpty() && !tcfe.getText().isEmpty()) {
                idcliente = Integer.parseInt(txidcli.getText());
                nc = Integer.parseInt(txnc.getText());
                String fe = tcfe.getText();
                t = obje.con5(idcliente, nc, fe);
                DefaultTableModel dtm = new DefaultTableModel();
                tablon.setModel(dtm);
                String titulos[] = {"Id T", "#Cuenta", "F. Transaccion", "T.Transaccion", "Monto", "ID Cliente", "Nombre",};

                dtm.setColumnIdentifiers(titulos);
                for (int i = 0; i < t.size(); i++) {
                    String valores[] = {String.valueOf(t.get(i).getIdtran()), String.valueOf(t.get(i).getNumcuenta()), t.get(i).getFechaTrans(), t.get(i).getTipoTrans(), String.valueOf(t.get(i).getMonto()), String.valueOf(t.get(i).getIdclie()), t.get(i).getNom()};
                    dtm.addRow(valores);
                }
                tablon.setModel(dtm);
            }
            if (txidcli.getText().isEmpty() && txnc.getText().isEmpty() && tcfe.getText().isEmpty() && !txan.getText().isEmpty()) {
                an = Integer.parseInt(txan.getText());
                t = obje.con9(an);
                DefaultTableModel dtm = new DefaultTableModel();
                tablon.setModel(dtm);
                String titulos[] = {"Id T", "#Cuenta", "F. Transaccion", "T.Transaccion", "Monto", "ID Cliente", "Nombre", "Des"};

                dtm.setColumnIdentifiers(titulos);
                for (int i = 0; i < t.size(); i++) {
                    String valores[] = {String.valueOf(t.get(i).getIdtran()), String.valueOf(t.get(i).getNumcuenta()), t.get(i).getFechaTrans(), t.get(i).getTipoTrans(), String.valueOf(t.get(i).getMonto()), String.valueOf(t.get(i).getIdclie()), t.get(i).getNom(), t.get(i).getDes()};
                    dtm.addRow(valores);
                }
                tablon.setModel(dtm);
            }
            if (!txidcli.getText().isEmpty() && !txnc.getText().isEmpty() && tcfe.getText().isEmpty() && !txan.getText().isEmpty()) {
                idcliente = Integer.parseInt(txidcli.getText());
                nc = Integer.parseInt(txnc.getText());
                an = Integer.parseInt(txan.getText());
                t = obje.con10(idcliente, nc, an);
                DefaultTableModel dtm = new DefaultTableModel();
                tablon.setModel(dtm);
                String titulos[] = {"Id T", "#Cuenta", "F. Transaccion", "T.Transaccion", "Monto", "ID Cliente", "Nombre",};

                dtm.setColumnIdentifiers(titulos);
                for (int i = 0; i < t.size(); i++) {
                    String valores[] = {String.valueOf(t.get(i).getIdtran()), String.valueOf(t.get(i).getNumcuenta()), t.get(i).getFechaTrans(), t.get(i).getTipoTrans(), String.valueOf(t.get(i).getMonto()), String.valueOf(t.get(i).getIdclie()), t.get(i).getNom()};
                    dtm.addRow(valores);
                }
                tablon.setModel(dtm);
            }
        } catch (RemoteException e) {
            System.out.println("Error de invocacion" + e);
        } catch (NotBoundException e) {
            System.out.println("Error de invocacion" + e);
        } catch (MalformedURLException e) {
            System.out.println("Error de invocacion" + e);
        }

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            interfazRemota obje = (interfazRemota) Naming.lookup("rmi://localhost:6060/obje");
            int mes, nc, an;
            ArrayList<transaccion> t = null;
            if (cbmes.getSelectedIndex() > 0) {
                mes = cbmes.getSelectedIndex();
                t = obje.con7(mes);
            }
            DefaultTableModel dtm = new DefaultTableModel();
            tablon.setModel(dtm);
            String titulos[] = {"Id T", "#Cuenta", "F. Transaccion", "T.Transaccion", "Monto", "ID Cliente", "Nombre", "Descripcion"};

            dtm.setColumnIdentifiers(titulos);
            for (int i = 0; i < t.size(); i++) {
                String valores[] = {String.valueOf(t.get(i).getIdtran()), String.valueOf(t.get(i).getNumcuenta()), t.get(i).getFechaTrans(), t.get(i).getTipoTrans(), String.valueOf(t.get(i).getMonto()), String.valueOf(t.get(i).getIdclie()), t.get(i).getNom(), t.get(i).getDes()};
                dtm.addRow(valores);
            }
            tablon.setModel(dtm);

        } catch (RemoteException e) {
            System.out.println("Error de invocacion" + e);
        } catch (NotBoundException e) {
            System.out.println("Error de invocacion" + e);
        } catch (MalformedURLException e) {
            System.out.println("Error de invocacion" + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            tablon.setModel(dtm);
            String titulos[] = {"#Cuenta", "Nombre", "Saldo", "Descripcion", "Fecha Expedicion"};

            dtm.setColumnIdentifiers(titulos);
            interfazRemota obje = (interfazRemota) Naming.lookup("rmi://localhost:6060/obje");
            double a, b;
            a = Double.parseDouble(txa.getText());
            b = Double.parseDouble(txb.getText());
            ArrayList<cuenta> lista = obje.con8(a, b);

            for (int i = 0; i < lista.size(); i++) {
                String[] valores = {String.valueOf(lista.get(i).getNumCuenta()), lista.get(i).getNombreC(), String.valueOf(lista.get(i).getSaldo()), lista.get(i).getDesC(), lista.get(i).getFechaCreacion()};

                dtm.addRow(valores);
            }
            tablon.setModel(dtm);
        } catch (RemoteException e) {
            System.out.println("Error de invocacion" + e);
        } catch (NotBoundException e) {
            System.out.println("Error de invocacion" + e);
        } catch (MalformedURLException e) {
            System.out.println("Error de invocacion" + e);
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            int numc = Integer.parseInt(txidc3.getText());
            interfazRemota obje = (interfazRemota) Naming.lookup("rmi://localhost:6060/obje");
            ArrayList<cuenta> lista = obje.con6(numc);
            String[] valores = new String[9];
            String[][] cuent = new String[3][lista.size()];
            String[] titulos2 = {"Cuenta", "ID.Cliente", "Cliente", "T.Cuenta", "Fecha Expedicion", "Saldo"};
            dtm.setColumnIdentifiers(titulos2);
            for (int i = 0; i < lista.size(); i++) {
                valores[0] = String.valueOf(lista.get(i).getNumCuenta());
                valores[1] = String.valueOf(lista.get(i).getIdcliente());
                valores[2] = (lista.get(i).getNombreC());
                valores[3] = lista.get(i).getDesC();
                valores[4] = lista.get(i).getFechaCreacion();
                valores[5] = String.valueOf(lista.get(i).getSaldo());
                cuent[0][i] = String.valueOf(lista.get(i).getIdtipocuenta());
                cuent[1][i] = String.valueOf(lista.get(i).getIdcliente());
                cuent[2][i] = String.valueOf(lista.get(i).getNumCuenta());

                dtm.addRow(valores);
            }
            tablon.setModel(dtm);
        } catch (RemoteException e) {
            System.out.println("Error de invocacion" + e);
        } catch (NotBoundException e) {
            System.out.println("Error de invocacion" + e);
        } catch (MalformedURLException e) {
            System.out.println("Error de invocacion" + e);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbmes;
    private javax.swing.JComboBox<String> cbtc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tablon;
    private javax.swing.JTextField tcfe;
    private javax.swing.JTextField txa;
    private javax.swing.JTextField txan;
    private javax.swing.JTextField txb;
    private javax.swing.JTextField txidc3;
    private javax.swing.JTextField txidcli;
    private javax.swing.JTextField txnc;
    // End of variables declaration//GEN-END:variables
}
